version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - "80:80"
      - "443:443"
    environment:
      - app.baseURL='http://staging-app.nginovasi.id/api/'
      - CI_ENVIRONMENT=development
      - database.default.hostname=103.59.95.133
      - database.default.port=3306
      - database.default.database=thishub
      - database.default.username=thishub
      - database.default.password=hcPWaD3ASLbq6Ry
      - database.default.DBDriver=MySQLi
    networks:
      - staging-app-network

networks:
  staging-app-network:
    driver: bridge