version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - "8080:80"
      - "443:443"
    environment:
      - DB_HOST=192.168.49.102
      - DB_NAME=gps_bus_db
      - DB_USER=gps_user
      - DB_PASS=Pe@29ebTTO9
      - DB_PORT=5000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge