version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: unless-stopped
    tty: true
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - 80:80
    working_dir: /var/www
    volumes:
      - app_storage:/var/www/storage/app
    environment:
      - CI_ENVIRONMENT=development
      - CI_DEBUG=true
      - app.baseURL='http://staging-app.nginovasi.id'
      - database.default.DBDriver=MySQLi
      - database.default.hostname=103.59.95.133
      - database.default.port=3306
      - database.default.database=sharebus
      - database.default.username=sharebus
      - database.default.password=BhXaepY85bA!2PNZ4
      - app.indexPage=''
      - app.forceGlobalSecureRequests=false
      - app.CSRFProtection=true
      - app.CSRFTokenName ='csrf_test_name'
      - app.CSRFCookieName='csrf_cookie_name'
      - app.CSRFCookieName='ci_cookies'
      - app.CSRFExpire=28800
      - app.CSRFRegenerate=false
      - app.CSRFRedirect=true
      - app.CSRFSamesite='Lax'
      - RECAPTCHA_SITE_KEY='6Leo_UspAAAAAPCNIA3FvfsQbip3-S3Qo2JjF_-V'
      - RECAPTCHA_SECRET_KEY='6Leo_UspAAAAAD3raqZ3BZDNtLk2utOX5q_yM2An'
      - jwt.secretkey= '539951a2f84941b5c0a23fbb35b628aae30b686fd138ace176ff3f1c0cbb100'
      - jwt.ttl=144
      - APP_NAMESPACE="HUBDAT Vehicles"
      - prop.appname="HUBDAT Vehicles"
      - prop.appdesc="Dashboard HUBDAT Vehicles"
      - prop.appshortdesc="Dashboard HUBDAT Vehicles"
      - prop.appauthor="NGI"
      - prop.applogo="/assets/img/hubdat.png"
      - prop.applogooperated="/assets/img/Logo_NGI.svg"
      - prop.apploginbg="/assets/images/hubdat.png"
      - prop.applogofull="/assets/img/hubdat.png"
      - prop.favicon="/assets/img/hubdat.png"
      - prop.primarycolor="#007bff"
      - prop.BASE_URL_STREAM_CCTV=https://stream-jatim-dev.tetrans.id
      - prop.DEFAULT_LATITUDE="-7.257241"
      - prop.DEFAULT_LONGITUDE="112.73726"
      - prop.DEFAULT_CITY="Jawa Timur, Indoneisa"
      - prop.BASE_URL_WHATSAPP_SERVICE=http://127.0.0.1:3000
      - prop.API_KEY_WHATSAPP_SERVICE=9da8b5054be143f99e1fca86be0e3ad5
      - prop.BASE_URL_NGI_GPS=https://gps.brtnusantara.com
      - prop.BASE_URL_NGI=https://devel74.nginovasi.id/akdpjatim
      - prop.NGI_USER="jtcc@mail.com"
      - prop.NGI_PASS="jatimjtcc99"
      - prop.PUSHER_APP_ID=1808731
      - prop.PUSHER_APP_KEY=ecb15884828a012229c8
      - prop.PUSHER_APP_SECRET=bc4d3f5ede97b4d3b95e
      - prop.PUSHER_HOST=
      - prop.PUSHER_PORT=443
      - prop.PUSHER_SCHEME=https
      - prop.PUSHER_APP_CLUSTER=ap1
      - prop.BROADCAST_DRIVER=pusher
      - prop.FILESYSTEM_DISK=minio
      - prop.MINIO_ACCESS_KEY_ID=AXDmTeagjure58e9sbNj
      - prop.MINIO_SECRET_ACCESS_KEY=HK9QHWAJxPqMjQzI5TZQLuyj6aFR9GiJ6HpQDvdU
      - prop.MINIO_DEFAULT_REGION=us-east-1
      - prop.MINIO_BUCKET=thishub-jatim
      - prop.MINIO_URL=https://object-storage.nginovasi.id
      - prop.MINIO_ENDPOINT=https://object-storage.nginovasi.id
      - prop.MAIL_MAILER=smtp
      - prop.MAIL_HOST=sandbox.smtp.mailtrap.io
      - prop.MAIL_PORT=2525
      - prop.MAIL_USERNAME=0369c017333ecb
      - prop.MAIL_PASSWORD=aba37299e23651
      - prop.MAIL_ENCRYPTION=tls
      - prop.MAIL_FROM_ADDRESS=smkdigitaljawatimur@gmail.com
      - prop.MAIL_FROM_NAME=SMKDIGITAL
    networks:
      - staging-app
  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - staging-app

networks:
  staging-app:
    driver: bridge

volumes:
  app_storage:
  redis_data:
